<?php
if ( ! function_exists( 'custom_upload_xml' ) ) {
	function custom_upload_xml( $mimes ) {
	    $mimes = array_merge( $mimes, array('xml' => 'application/xml') );
	    return $mimes;
	}
}
add_filter('upload_mimes', 'custom_upload_xml');

/*  AddOns Options 
   ..................................... */
if ( ! function_exists( 'addonsadmin_menu' ) ) {
	function addonsadmin_menu() {
		$icon_url = get_template_directory_uri()."/admin/img/addons.png";		
		add_menu_page('Addons', 'Addons', 'manage_options', 'addons',  'addOns', $icon_url, 21);
		add_submenu_page('addons', 'Mailchimp', 'Mailchimp', 'manage_options', 'mailchimp', 'addons_mailchimp');
		add_submenu_page('addons', 'Facebook', 'Facebook', 'manage_options', 'facebook', 'addons_facebook');
		add_submenu_page('addons', 'Custom Icons', 'Custom Icons', 'manage_options', 'custom_icons', 'addons_icons');
		add_submenu_page('addons', 'Price Range', 'Price Range', 'manage_options', 'price-range', 'addons_price_range');
		add_submenu_page('addons', 'Community Polls', 'Community Polls', 'manage_options', 'community-polls', 'addons_community_polls');
		add_submenu_page('addons', 'Import/Export Taxonomy', 'Import/Export Taxonomy', 'manage_options', 'export-category', 'addons_export');
		add_submenu_page('addons', 'Import/Export Gallery', 'Import/Export Gallery', 'manage_options', 'gallery-import-export', 'addons_gallery_export_import');
	}
}
add_action('admin_menu', 'addonsadmin_menu');

if ( ! function_exists( 'update_guid' ) ) {
	function update_guid( $old_url, $new_url ) {
		global $wpdb;	
		$wpdb->query( "UPDATE ".$wpdb->prefix."posts SET guid = replace(guid, '".$old_url."','".$new_url."')" );
		$wpdb->query( "UPDATE ".$wpdb->prefix."postmeta SET meta_value = replace(meta_value, '".$old_url."','".$new_url."')" );

	}
}

if ( ! function_exists( 'entrada_post_id_from_slug' ) ) {
	function entrada_post_id_from_slug($post_slug) {
		global $wpdb;
		$rw = $wpdb->get_row("select * from ".$wpdb->prefix."posts where post_name ='".$post_slug."'" );
		return $rw->ID;	
	}
}

if ( ! function_exists( 'addons_gallery_export_import' ) ) {
	function addons_gallery_export_import() {
		global $wpdb;
		$msg = '';
		
		if(isset($_POST['import_gallery']) && $_POST['import_gallery'] != ''){
			if ( ! function_exists( 'wp_handle_upload' ) ) {
	   			require_once( ABSPATH . 'wp-admin/includes/file.php' );
			}
			$uploadedfile = $_FILES['gallery_file'];
			
			$upload_overrides = array( 'test_form' => false );
			
			$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
			
			if ( $movefile && ! isset( $movefile['error'] ) ) {
				$msg =  "Custom gallery images has been successfully imported.\n";
				 $file_path = $movefile['file'];
				 $file_url = $movefile['url'];
				/* Update taxonomy ........... */
				$upload_dir = wp_upload_dir();
				if(file_exists($file_path)){
					$xml = simplexml_load_file($file_path);
					$cnt = 0;
					foreach($xml->item as $item)  {
						$attached_arr = array();
						if(!empty($item->attach_url)){
							$post_id = entrada_post_id_from_slug( $item->post_slug );
							
							$attach_urls  = explode(',', $item->attach_url);
							foreach($attach_urls as $attach_url) {
								$image_url = str_replace($item->domain_url, esc_url( home_url( '' ) ) , $attach_url);
								$attached_arr[] = entrada_attachment_id_from_src($image_url);
							}
							
							if( $item->meta_key == 'product_gallery_img' ) {
								update_post_meta($post_id, 'product_gallery_img', maybe_serialize($attached_arr));
							}
							else if( $item->meta_key == 'itinerary_gallery_img' ) {
								update_post_meta($post_id, 'itinerary_gallery_img', maybe_serialize($attached_arr));
							}
						}
					}
				}
			}
			else {
				/**
				 * Error generated by _wp_handle_upload()
				 * @see _wp_handle_upload() in wp-admin/includes/file.php
				 */
				$msg =  $movefile['error'];
			}	
		}	
		echo '<div id="wrap"><div class="wrap"><h2><img src="'.get_template_directory_uri().'/admin/img/addons.png"> '. __("Addons", "entrada") .'</h2></div>';
		echo '<div class="wrap">';
		
		if(!empty($msg)){
			echo '<p class="update-nag notice">'.$msg.'</p>';
		} ?>
	    <table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
	    	<tr><td><h3> Export Gallery</h3></td></tr>
	        <tr><td> <p>  Click below to generate a .xml file for tour gallery. </p> </td></tr>    
	    	<tr><td><?php echo '<a href="'.get_template_directory_uri().'/admin/feed/gallery-data.php" target="_blank" class="button-primary">'. __("Export Gallery", "entrada") .'</a>';?></td></tr>
	    </table>  
	    <form action="" method="post" enctype="multipart/form-data">  
	    <table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
	   		<tr><td><h3><?php _e('Import Gallery', 'entrada'); ?></h3></td></tr>
	        <tr><td><p><?php _e(' Please select a .xml file generated.', 'entrada'); ?></p></td></tr>
	    	<tr>
	    		<td>
		    		<input type="file" name="gallery_file">
	     		</td>
	     	</tr>
	        <tr><td> <input type="submit" value="<?php esc_attr_e('Import Gallery', 'entrada'); ?>" name="import_gallery"  class="button-primary" > </td></tr>
	    </table> 
		</form>
		<?php 
		echo '</div></div>';	
	}
}

if ( ! function_exists( 'addons_export' ) ) {
	function addons_export() {
		global $wpdb;
		$msg = '';
		if(isset($_POST['import_taxonomy']) && $_POST['import_taxonomy'] != '') {
			if ( ! function_exists( 'wp_handle_upload' ) ) {
	   			require_once( ABSPATH . 'wp-admin/includes/file.php' );
			}
			$uploadedfile = $_FILES['taxonomy_file'];
			
			$upload_overrides = array( 'test_form' => false );
			
			$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
			
			if ( $movefile && ! isset( $movefile['error'] ) ) {
				$msg =  "Custom taxonomy data has been successfully imported.\n";
				 $file_path = $movefile['file'];
				 $file_url = $movefile['url'];
				/* Update taxonomy ........... */
				$upload_dir = wp_upload_dir();
				if(file_exists($file_path)){
					$xml = simplexml_load_file($file_path);
					$cnt = 0;
					foreach($xml->item as $item)  {
						$cnt++;					
						if($cnt == 1){
							$old_url = $item->cat_url;
							$new_url = esc_url( home_url( '' ) );
							update_guid($old_url, $new_url);
						}
						
						$array_data = array(
							'prod_cat_best_season' => '',
							'prod_cat_popular_location' => '',
							'prod_cat_heading' => '',
							'prod_cat_sub_heading' => '',
							'prod_cat_sub_title' => '',
							'prod_cat_listing_title' => '',
							'prod_cat_listing_sub_title' => '',
							'prod_cat_dig_more_link' => '',
							'product_cat_banner_img_id' => '',
							'product_cat_map_img_id' => '',
							'prod_iconbar_cat_val' => '',
							'prod_featured_home_val' => '',
							'prod_featured_cat_val' => '',
							'prod_icomoon_cat_val' => '',
							'activity_level_val' => ''	
						);
						
						$cat_data = unserialize($item->cat_data);	
								
						if(!empty($item->cat_slug)) {
							/* Filter data ........... */
							if( count($cat_data) > 0) {
								foreach( (array)$cat_data as $key=>$key_value){
									if (array_key_exists($key, $array_data)) {
										$val = $key_value;
										if(!empty($key_value) && ($key == 'product_cat_banner_img_id' || $key == 'product_cat_map_img_id' ) ){
												
										
											$image_url = $upload_dir['baseurl'].$key_value;											
											$attachment_id = entrada_attachment_id_from_src($image_url);
											$val = $attachment_id;
										}
										$array_data[$key] = $val;
									}									
								}
							}
							
							$slug_data = explode("==",$item->cat_slug);			
							$term = get_term_by('slug', $slug_data[0], $slug_data[1]);						
							$option_name = 'taxonomy_'.$term->term_id;
							update_option( $option_name, $array_data );
							
							// Taxonomy Featured Image Update....
							if(!empty($item->cat_img)) {
								$featured_img_src = $upload_dir['baseurl'].$item->cat_img;
								$attach_id = entrada_attachment_id_from_src($featured_img_src);
								if(!empty($attach_id)) {
									update_woocommerce_term_meta( $term->term_id, 'thumbnail_id', $attach_id, true);
								}
							}
						
						}						
					}
				}
					
			}
			else {
				/**
				 * Error generated by _wp_handle_upload()
				 * @see _wp_handle_upload() in wp-admin/includes/file.php
				 */
				$msg =  $movefile['error'];
			}	
		}	
		
		echo '<div id="wrap"><div class="wrap"><h2><img src="'.get_template_directory_uri().'/admin/img/addons.png"> '. __("Addons", "entrada") .'</h2></div>';
		echo '<div class="wrap">';		
	    if(!empty($msg)){
			echo '<p class="update-nag notice">'.$msg.'</p>';
		} ?>
	    <table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
	    	<tr><td><h3> <?php _e('Export Taxonomy Data', 'entrada'); ?></h3></td></tr>
	    	<tr><td><?php echo '<a href="'.get_template_directory_uri().'/admin/feed/taxonomy-data.php" target="_blank" class="button-primary">'. __("Export Taxonomy Data", "entrada") .'</a>';?></td></tr>        
	    </table>    
	    <table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
	   		<tr><td><h3><?php _e('Import Taxonomy Data', 'entrada'); ?></h3></td></tr>
	    	<tr>
	    		<td>
	    			<form action="" method="post" enctype="multipart/form-data">
		    			<?php _e('Upload XML Files', 'entrada'); ?> <input type="file" name="taxonomy_file">
		            	<input type="submit" value="<?php esc_attr_e('Import Taxonomy Data', 'entrada'); ?>" name="import_taxonomy"  class="button-primary" >
	    			</form>
	     		</td>
	     	</tr>
	    </table>    
	<?php
		echo '</div></div>';
	}
}

if ( ! function_exists( 'addOns' ) ) {
	function addOns() {
		global $wpdb; 	
		echo '<div id="wrap"><div class="wrap"><h2><img src="'.get_template_directory_uri().'/admin/img/addons.png"> Addons</h2></div>';
		echo '<div class="wrap">';	
			echo '<ul class="entrada-addons">';
				echo '<li><a href="'.admin_url('admin.php?page=mailchimp').'"><span class="img-wrap"><img src="'.get_template_directory_uri().'/admin/img/icon-mailchimp.png"></span> '. __("Mailchimp", "entrada") .'</a></li>';
				echo '<li><a href="'.admin_url('admin.php?page=facebook').'"><span class="img-wrap"><img src="'.get_template_directory_uri().'/admin/img/icon-facebook.png"></span>'. __("Facebook", "entrada") .'</a></li>';
				echo '<li><a href="'.admin_url('admin.php?page=price-range').'"><span class="img-wrap"><img src="'.get_template_directory_uri().'/admin/img/icon-price-tag.png"></span>'. __("Price Range", "entrada") .'</a></li>';
				echo '<li><a href="'.admin_url('admin.php?page=community-polls').'"><span class="img-wrap"><img src="'.get_template_directory_uri().'/admin/img/icon-poll.png"></span>'. __("Community Polls", "entrada") .'</a></li>';
			echo '</ul>';	
		echo '</div>';		
		echo '</div>';	
	}
}

/*  AddOns => Facebook 
  ..................................... */
if ( ! function_exists( 'addons_facebook' ) ) {
	function addons_facebook() {
		global $wpdb; 
		$settings = array();	
		$page = isset($_REQUEST['page'])?$_REQUEST['page']:'';
		$mode = isset($_REQUEST['mode'])?$_REQUEST['mode']:'';
		$message = '';	
		$page_title = 'Facebook Settings';
		$page_subtitle = 'Facebook Settings';			
		/* Widget : API Key */
		$settings[] = array(
						'title'   		=> __( 'Facebook App ID', 'entrada'  ),
						'entrada_key' 	=> 'entrada_facebook_app_id',
						'desc'    		=> __( 'Please set app ID (Example : 1530139877297980 ). ', 'entrada'  ),
						'type' 			=> 'text',
						'std'     		=> '',
						'hint' 			=> '',
					);
		if( isset( $_POST['bannerbtn'] ) ) {
			foreach( $settings as $setting ) {
				if( array_key_exists( 'entrada_key', $setting ) ) {
					$field_val = $setting['entrada_key'];
					update_option( $setting['entrada_key'], $_POST[$field_val] );
				}		  
			}
			$message = __( 'Setting has successfully saved.', 'entrada' );
		} ?>
		<div id="wrap">
	    	<div class="wrap"><h2><img src="<?php echo get_template_directory_uri(); ?>/admin/img/addons.png"> <?php echo $page_title; ?> </h2>
	        </div>
		<?php
			if(isset( $message ) && $message != '') :	
				echo '<div class="wrap"><div id="message" class="updated" style="margin-left:0;">';
				echo '<p>'.$message.'</p>';
				echo '</div></div>';
			endif; ?>
	    	<div class="wrap">
		        <?php if( count($settings)) { ?>
		        <form name="bannerfrm" action="" method="post" enctype="multipart/form-data">
		        	<table width="100%" class="widefat fixed comments" style="padding-bottom:20px;">
						<thead>
							<tr>
								<th width="20%"> <strong> <?php echo $page_subtitle; ?> </strong> </th>
								<th width="80%;">&nbsp;  </th>
							</tr>
						</thead>
						<tbody>
						<?php
							foreach($settings as $setting) {
								switch ($setting['type']) {
									case 'heading':
										echo '<tr><td colspan="2"> <h4>'.$setting['title'].'</h4> </td></tr> ';
									break;
									case 'select':
										$seelcted_val = get_option( $setting['entrada_key'] );
										echo '<tr><td width="20%"><label>'.$setting['title'].'</label> </td><td  width="80%"><select name="'.$setting['entrada_key'].'" id="'.$setting['entrada_key'].'">';
										if(count($setting['choices']) > 0){
											foreach( $setting['choices'] as $key => $val) {
												echo '<option value="'.$key.'"';	
												if( isset($seelcted_val) && $key == $seelcted_val ){
													echo ' selected = "selected"';
												}
												echo ' >'.$val.'</option>';
											}
										}
										echo '</select></td></tr>';
									break;
									default :
										echo '<tr><td width="20%"><label>'.$setting['title'].'</label> </td>
										<td  width="80%"><input type="text"  style="width:350px;" name="'.$setting['entrada_key'].'" id="'.$setting['entrada_key'].'" value="'.get_option( $setting['entrada_key'] ).'"><span> '.$setting['desc'].'</span></td>
										</tr> ';
								}
							} ?>
							<tr>
								<td width="20%">&nbsp;</td>
								<td  width="80%"> <input class="button button-primary button-large" type="submit" name="bannerbtn"  value="<?php esc_attr_e( 'Save Changes', 'entrada' ); ?>" style="cursor:pointer;" /></td>
							</tr>
		  
							<tr>
								<td colspan="2">
								<?php 
									$thisurl = 'https://developers.facebook.com/docs/apps/register';
									echo sprintf( wp_kses( __( 'You\'ll need Facebook App ID to share post on Facebook. If you don\'t have App ID, please <a href="%s">Get Facebook APP ID</a> now . Skip this step, if you already updated App ID.', 'entrada' ), array(  'a' => array( 'href' => array() ) ) ), esc_url( $thisurl ) ); ?>
								</td>
							</tr>
						</tbody>
					</table>
				</form>
				<?php } ?>        
	        </div>
	    </div>
	<?php
	}
}

/* AddOns => Custom Icons 
   ..................................... */
if ( ! function_exists( 'addons_icons' ) ) {
	function addons_icons() {
		global $wpdb;
		$page = isset($_REQUEST['page'])?$_REQUEST['page']:'';
		$mode = isset($_REQUEST['mode'])?$_REQUEST['mode']:'';
		$message = '';
			
		$entrada_icons = array();
		$entrada_icons = get_option( 'entrada_icons' );
		if(!empty ( $entrada_icons ) ){
			$entrada_icons = get_option( 'entrada_icons' );
		}	
			
		if( isset( $_POST['iconsave_btn'] ) ) { 		
			
			$entrada_temp_icons = array();
			$entrada_ico_title = sanitize_title( $_POST['entrada_ico_title'] );
			$entrada_temp_icons[$entrada_ico_title] = addslashes($_POST['entrada_ico_class']);
			$entrada_temp_icons = array_merge($entrada_icons,$entrada_temp_icons);
				
			update_option( 'entrada_icons', $entrada_temp_icons  );
			
			$message = __( 'Icon has been saved.', 'entrada' );
		}
		
		if( $mode == 'delete' ){
			$entrada_ico_key = $_REQUEST['pid'];
			unset($entrada_icons[$entrada_ico_key]);
			update_option( 'entrada_icons', $entrada_icons  );
			
			$message = __('Icon has been deleted.', 'entrada');
		}
		
		$entrada_icons = get_option( 'entrada_icons' );
		ksort($entrada_icons);
		?>
	    <div id="wrap">
			<div class="wrap">
				<h2>
					<img src="<?php echo get_template_directory_uri(); ?>/admin/img/addons.png"> <?php _e('Custom Icomoon Settings', 'entrada'); ?>
					<a href="<?php echo $_SERVER["PHP_SELF"]?>?page=custom_icons&mode=add" class="button button-primary button-small" ><?php _e('Add New', 'entrada'); ?></a> 
				</h2>
			</div>
	        
	        	<?php
			if(isset( $message ) && $message != '') :	
				echo '<div class="wrap"><div id="message" class="updated" style="margin-left:0;">';
				echo '<p>'.$message.'</p>';
				echo '</div></div>';
			endif; ?>
	        
	        <table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
				<tr>
					<td width="50%" > 
						<table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
							<form name="bannerfrm" action="" method="post" enctype="multipart/form-data">
						<?php 
							if($mode=='edit'){
								$entrada_ico_title = $_REQUEST['pid'];
							} ?>
								<thead>
									<tr>
										<th colspan="2" >
										<strong>
										<?php
											if($mode=='edit') {
												echo __( 'Update', 'entrada' );
											}
											else { 
												echo __( 'Add', 'entrada' );
											}
											_e( ' Custom Icon', 'entrada' ); ?>
										</strong>
										</th>
									</tr>
								</thead>							
								<tbody>
									<tr>
										<td><label> <?php _e( 'Icon Title', 'entrada' ); ?> : </label> </td>
										<td>
											<input type="text" name="entrada_ico_title" style="width:200px;"  id="entrada_ico_title" value="<?php if( $mode == 'edit' ) { echo stripslashes($_REQUEST['pid']); } ?>"  />
								
										</td>
									</tr>
									<tr>
										<td><label>  <?php _e( 'Icon Class Name', 'entrada' ); ?> : </label></td>
										<td><input type="text" name="entrada_ico_class" style="width:200px;"  id="entrada_ico_class" value="<?php if($mode=='edit') { echo stripslashes($entrada_icons[$entrada_ico_title]); }?>"  /></td>
									</tr>
							  			 
							  
									<tr>
										<td>&nbsp; </td>
										<td><input type="submit" class="button button-primary button-large" name="iconsave_btn"  value=" <?php esc_attr_e( 'Save', 'entrada' ); ?>" style="cursor:pointer;" /></td>
									</tr>
								</tbody>
							   
								<tfoot>
									<tr>
										<th  colspan="2"><strong> <?php _e( 'Note', 'entrada' ); ?></strong> :  <?php _e( 'Please avoid blank space.', 'entrada' ); ?> </th>
									</tr>
								</tfoot>
							  
							</form>
						</table>
					</td>
					<td width="50%">
						<table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
							<thead>
								<tr>
									<th width="13%">#</th>
									<th width="25%"><?php _e( 'Icon Title', 'entrada' ); ?> </th>
									<th width="40%"><?php _e( 'Icon Class Name', 'entrada' ); ?></th>
									<th width="22%"><?php _e( 'Action', 'entrada' ); ?></th>
								</tr>
							</thead>
							<tbody>
						<?php
						
							if( $entrada_icons ) {
								$currency_symbol = get_woocommerce_currency_symbol();
								$count = 1;
								$class = '';
								foreach( $entrada_icons as $key => $value ) {
									if($count%2 == 1){
										$class = 'class="alternate "';
									}
									else{
										$class = '';
									} ?>
								<tr <?php echo $class; ?>>
									<td><?php echo $count; ?></td>
									<td><?php echo stripslashes($key); ?></td> 
									<td><span class="<?php echo stripslashes($value); ?>" ></span> <?php echo stripslashes($value); ?></td>
								 
									<td> <a href="<?php echo $_SERVER["PHP_SELF"]?>?page=<?php echo $page;?>&pid=<?php echo $key;?>&mode=edit">Edit</a> | <a href="<?php echo $_SERVER["PHP_SELF"]?>?page=<?php echo $page;?>&pid=<?php echo $key;?>&mode=delete" onclick="return confirm('Are you sure you want to delete?')">Delete </a></td>
								</tr> 
								<?php
									$count++;
								}
							}
							else { ?>
								<tr class="alternate ">
									<td colspan="4"><?php _e( 'No Record Found.', 'entrada' ); ?></td>
								</tr>
						<?php } ?>
							</tbody>
							<tfoot>
								<tr>
									<th width="13%">#</th>
									<th width="25%"><?php _e( 'Icon Title', 'entrada' ); ?> </th>
									<th width="40%"><?php _e( 'Icon Class Name', 'entrada' ); ?></th>
									<th width="22%"><?php _e( 'Action', 'entrada' ); ?></th>
								</tr>
							</tfoot>
						</table>
					</td>
				</tr>
			</table>
	        
	    </div>    
	    
	    <?php	

	}
}
/*  AddOns => Mailchimmp 
   ..................................... */
if ( ! function_exists( 'addons_mailchimp' ) ) {
	function addons_mailchimp() {
		global $wpdb; 
		$settings = array();	
		$page = isset($_REQUEST['page'])?$_REQUEST['page']:'';
		$mode = isset($_REQUEST['mode'])?$_REQUEST['mode']:'';
		$message = '';
		
		$page_title = __( 'Mailchimp Settings', 'entrada' );
		$settings[] = array(
						'title'	=> __( 'Subscribe Form for Widget/Sidebar', 'entrada'  ),
						'type'	=> 'heading',
						'std'	=> '',
						'hint'	=> ''
					);
		
		/* Widget : API Key */			
		$settings[] = array(
						'title'   		=> __( 'API Key', 'entrada'  ),
						'entrada_key' 	=> 'widget_mailchimp_api_key',
						'desc'    		=> __( 'Please set api key.', 'entrada'  ),
						'type' 			=> 'text',
						'std'     		=> '',
						'hint'			 => ''
					);	
		/* Widget : List ID / Group ID */			
		$settings[] = array(
						'title'   		=> __( 'List ID / Group ID', 'entrada'  ),
						'entrada_key' 	=> 'widget_mailchimp_list_id',
						'desc'    		=> __( 'Please set list ID / group ID.', 'entrada'  ),
						'type' 			=> 'text',
						'std'     		=> '',
						'hint' 			=> ''
					);	
		
		/* Widget : Send Welcome email ? */		
		$settings[] = array(
						'title'   		=> __( 'Send Welcome email ?', 'entrada'  ),
						'entrada_key' 	=> 'widget_mailchimp_send_welcome_email',
						'desc'   		=> __( '', 'entrada'  ),
						'type' 			=> 'select',
						'std'     		=> '',
						'hint' 			=> '',
						'choices' 		=> array(
											'true'	=> 'Yes',
											'false'	=> 'No'
										)
					);	
					
		/* Widget : Allow duplicate Entry ? */		
		$settings[] = array(
						'title'   		=> __( 'Allow Double Entry ?', 'entrada'  ),
						'entrada_key' 	=> 'widget_mailchimp_double_entry',
						'desc'    		=> __( '', 'entrada'  ),
						'type' 			=> 'select',
						'std'     		=> '',
						'hint' 			=> '',
						'choices' 		=> array(
											'false'	=> 'No',
											'true'	=> 'Yes'
										)
					);	
					
		/* Widget : Allow duplicate Entry ? */
		$settings[] = array(
						'title'   		=> __( 'Email format :', 'entrada'  ),
						'entrada_key' 	=> 'widget_mailchimp_email_format',
						'desc'    		=> __( '', 'entrada'  ),
						'type' 			=> 'select',
						'std'     		=> '',
						'hint' 			=> '',
						'choices' 		=> array(
											'html'	=> 'HTML',
											'text'	=> 'TEXT'
										)
					);			
		
		/* Footer Section ................... */	
		$settings[] = array(
							'title'	=> __( 'Subscribe Form for Footer', 'entrada'  ),
							'type'	=> 'heading',
							'std'	=> '',
							'hint'	=> ''
					);
			
		/* Footer : API Key */			
		$settings[] = array(
						'title'   		=> __( 'API Key', 'entrada'  ),
						'entrada_key' 	=> 'footer_mailchimp_api_key',
						'desc'    		=> __( 'Please set api key.', 'entrada'  ),
						'type' 			=> 'text',
						'std'    		=> '',
						'hint'			=> ''
				);	
		/* Widget : List ID / Group ID */			
		$settings[] = array(
						'title'   		=> __( 'List ID / Group ID', 'entrada'  ),
						'entrada_key' 	=> 'footer_mailchimp_list_id',
						'desc'    		=> __( 'Please set list ID / group ID.', 'entrada'  ),
						'type' 			=> 'text',
						'std'     		=> '',
						'hint' 			=> ''
				);	
		
		/* Widget : Send Welcome email ? */		
		$settings[] = array(
						'title'   		=> __( 'Send Welcome email ?', 'entrada'  ),
						'entrada_key' 	=> 'footer_mailchimp_send_welcome_email',
						'desc'    		=> __( '', 'entrada'  ),
						'type' 			=> 'select',
						'std'     		=> '',
						'hint' 			=> '',
						'choices' 		=> array(
											'true'	=> 'Yes',
											'false'	=> 'No'
										)
					);	
					
		/* Widget : Allow duplicate Entry ? */		
		$settings[] = array(
						'title'   		=> __( 'Allow Double Entry ?', 'entrada'  ),
						'entrada_key' 	=> 'footer_mailchimp_double_entry',
						'desc'    		=> __( '', 'entrada'  ),
						'type' 			=> 'select',
						'std'     		=> '',
						'hint' 			=> '',
						'choices' 		=> array(
											'false'	=> 'No',
											'true'	=> 'Yes'
										)
					);	
					
		/* Widget : Allow duplicate Entry ? */		
		$settings[] = array(
						'title'   		=> __( 'Email format :', 'entrada'  ),
						'entrada_key' 	=> 'footer_mailchimp_email_format',
						'desc'    		=> __( '', 'entrada'  ),
						'type' 			=> 'select',
						'std'     		=> '',
						'hint' 			=> '',
						'choices' 		=> array(
											'html' => 'HTML',
											'text' => 'TEXT'
										)
					);
		if( isset( $_POST['bannerbtn'] ) ) {
			foreach( $settings as $setting ) {
				if( array_key_exists('entrada_key', $setting ) ) {
					$field_val = $setting['entrada_key'];
					update_option( $setting['entrada_key'], $_POST[$field_val] );				
				}
			}
			  $message = __( 'Setting has successfully saved.', 'entrada' );
		} ?>
		<div id="wrap">
	    	<div class="wrap">
	    		<h2><img src="<?php echo get_template_directory_uri(); ?>/admin/img/addons.png"> <?php _e( 'Mailchimp Settings', 'entrada' ); ?> </h2>
	        </div>
	        <?php
	        	if(isset( $message ) && $message != '') :
					echo '<div class="wrap"><div id="message" class="updated" style="margin-left:0;">';
					echo '<p>'.$message.'</p>';
					echo '</div></div>';
				endif; ?>        
	    	<div class="wrap">
	        <?php if( count($settings)) { ?>        
				<form name="bannerfrm" action="" method="post" enctype="multipart/form-data">
					<table width="100%" class="widefat fixed comments" style="padding-bottom:20px;">
						<thead>
							<tr>
								<th width="20%"> <strong> <?php echo $page_title; ?> </strong> </th>
								<th width="80%;">&nbsp;  </th>
							</tr>
						</thead>
						<tbody>
					<?php
						foreach($settings as $setting) {			
							switch ($setting['type']) {							
								case 'heading':
									echo '<tr><td colspan="2"> <h4>'.$setting['title'].'</h4> </td></tr> ';
								break;
								
								case 'select':
									$seelcted_val = get_option( $setting['entrada_key'] );
									echo '<tr><td width="20%"><label>'.$setting['title'].'</label> </td><td  width="80%"><select name="'.$setting['entrada_key'].'" id="'.$setting['entrada_key'].'">';
									if(count($setting['choices']) > 0){								
										foreach( $setting['choices'] as $key => $val) {
											echo '<option value="'.$key.'"';	
											if( isset($seelcted_val) && $key == $seelcted_val ){
												echo ' selected = "selected"';
											}
											echo ' >'.$val.'</option>';
										}
									}							
									echo '</select></td></tr>';
								break;
								
								default :
									echo '<tr><td width="20%"><label>'.$setting['title'].'</label> </td>
									 <td  width="80%"><input type="text"  style="width:350px;" name="'.$setting['entrada_key'].'" id="'.$setting['entrada_key'].'" value="'.get_option( $setting['entrada_key'] ).'"><span> '.$setting['desc'].'</span></td>
									</tr> ';						
							}
						} ?>
							<tr>
								<td width="20%">&nbsp;</td>
								<td  width="80%"> <input class="button button-primary button-large" type="submit" name="bannerbtn"  value="<?php esc_attr_e('Save Changes', 'entrada'); ?>" style="cursor:pointer;" /></td>
							</tr>
		  
							<tr>
								<td colspan="2">
								<?php 
									$thisurl = 'http://kb.mailchimp.com/accounts/management/about-api-keys';
									echo sprintf( wp_kses( __( 'If you want to set up an integration with your MailChimp account, chances are high that you\'ll need to generate an API key.<a href="%s">Get API Key.</a>', 'entrada' ), array(  'a' => array( 'href' => array() ) ) ), esc_url( $thisurl ) ); ?>
								</td>
							</tr>
						</tbody>
					</table>
				</form>        
			<?php } ?>        
	        </div>
	    </div>
	<?php
	}
}

/*  AddOns => Price Range 
   ..................................... */
if ( ! function_exists( 'addons_price_range' ) ) {
	function addons_price_range() {	 
		global $wpdb;
		$page = isset($_REQUEST['page'])?$_REQUEST['page']:'';
		$mode = isset($_REQUEST['mode'])?$_REQUEST['mode']:'';
		$message = '';	
		if( isset( $_POST['bannerbtn'] ) ) { 
			if( $mode=='edit' ){			
				$wpdb->update($wpdb->prefix.'entrada_price_range',array('pr_title'=>addslashes($_POST['pr_title']), 'min_price'=>$_POST['min_price'], 'max_price'=>$_POST['max_price']) , array('id'=>$_POST['bannerid'])); 	
			}
			else{
				$wpdb->insert($wpdb->prefix.'entrada_price_range', array('pr_title'=>addslashes($_POST['pr_title']), 'min_price'=>$_POST['min_price'] , 'max_price'=>$_POST['max_price']) );
			}
			$message = __( 'Record has been saved.', 'entrada' );
		}	
		if( $mode == 'delete' ){
			$wpdb->query("delete from ".$wpdb->prefix."entrada_price_range where id=$_REQUEST[pid]");
			$message = __('Record has been deleted.', 'entrada');
		} ?>
		<div id="wrap">
			<div class="wrap">
				<h2>
					<img src="<?php echo get_template_directory_uri(); ?>/admin/img/addons.png"> <?php _e('Price Range Settings', 'entrada'); ?>
					<a href="<?php echo $_SERVER["PHP_SELF"]?>?page=price-range&mode=add" class="button button-primary button-small" ><?php _e('Add New', 'entrada'); ?></a> 
				</h2>
			</div>
		<?php if(!empty($message)) : ?>
				<div class="wrap"><div id="message" class="updated" style="margin-left:0; padding:10px;"><?php echo $message; ?></div></div>
		<?php endif; ?>
			<table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
				<tr>
					<td width="50%" > 
						<table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
							<form name="bannerfrm" action="" method="post" enctype="multipart/form-data">
						<?php 
							if($mode=='edit'){
								$result_update = $wpdb->get_row("select * from ".$wpdb->prefix."entrada_price_range where id=$_REQUEST[pid]");
							} ?>
								<thead>
									<tr>
										<th colspan="2" >
										<strong>
										<?php
											if($mode=='edit') {
												echo __( 'Update', 'entrada' );
											}
											else { 
												echo __( 'Add', 'entrada' );
											}
											_e( 'Price Range', 'entrada' ); ?>
										</strong>
										</th>
									</tr>
								</thead>							
								<tbody>
									<tr>
										<td><label> <?php _e( 'Title', 'entrada' ); ?> : </label> </td>
										<td>
											<input type="text" name="pr_title" style="width:200px;"  id="pr_title" value="<?php if( $mode == 'edit' ) { echo stripslashes($result_update->pr_title); } ?>"  />
											<input type="hidden" name="bannerid" value="<?php if($mode=='edit')echo $result_update->id;?>" />
										</td>
									</tr>
									<tr>
										<td><label>  <?php _e( 'Min. Price', 'entrada' ); ?> : </label></td>
										<td><input type="text" name="min_price" style="width:200px;"  id="min_price" value="<?php if($mode=='edit') { echo stripslashes($result_update->min_price); }?>"  /></td>
									</tr>
							  
									<tr>
										<td><label>  <?php _e( 'Max. Price', 'entrada' ); ?> : </label></td>
										<td><input type="text" name="max_price" style="width:200px;"  id="max_price" value="<?php if($mode=='edit') { echo stripslashes($result_update->max_price); }?>"  /></td>
									</tr>				 
							  
									<tr>
										<td>&nbsp; </td>
										<td><input type="submit" class="button button-primary button-large" name="bannerbtn"  value=" <?php esc_attr_e( 'Save', 'entrada' ); ?>" style="cursor:pointer;" /></td>
									</tr>
								</tbody>
							   
								<tfoot>
									<tr>
										<th  colspan="2"><strong> <?php _e( 'Note', 'entrada' ); ?></strong> :  <?php _e( 'Please avoid currency sign and decimal value.', 'entrada' ); ?> </th>
									</tr>
								</tfoot>
							  
							</form>
						</table>
					</td>
					<td width="50%">
						<table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
							<thead>
								<tr>
									<th width="13%">#</th>
									<th width="25%"><?php _e( 'Title', 'entrada' ); ?> </th>
									<th width="40%"><?php _e( 'Price Range', 'entrada' ); ?></th>
									<th width="22%"><?php _e( 'Action', 'entrada' ); ?></th>
								</tr>
							</thead>
							<tbody>
						<?php
							$result = $wpdb->get_results("select * from ".$wpdb->prefix."entrada_price_range WHERE 1= 1 order by min_price ASC ");
							if( $result ) {
								$currency_symbol = get_woocommerce_currency_symbol();
								$count = 1;
								$class = '';
								foreach( $result as $entry ) {
									if($count%2 == 1){
										$class = 'class="alternate "';
									}
									else{
										$class = '';
									} ?>
								<tr <?php echo $class; ?>>
									<td><?php echo $count; ?></td>
									<td><?php echo stripslashes($entry->pr_title); ?></td> 
									<td><?php echo $currency_symbol.stripslashes($entry->min_price); ?> - <?php echo $currency_symbol.stripslashes($entry->max_price); ?></td>
								 
									<td> <a href="<?php echo $_SERVER["PHP_SELF"]?>?page=<?php echo $page;?>&pid=<?php echo $entry->id;?>&mode=edit">Edit</a> | <a href="<?php echo $_SERVER["PHP_SELF"]?>?page=<?php echo $page;?>&pid=<?php echo $entry->id;?>&mode=delete" onclick="return confirm('Are you sure you want to delete?')">Delete </a></td>
								</tr> 
								<?php
									$count++;
								}
							}
							else { ?>
								<tr class="alternate ">
									<td colspan="4"><?php _e( 'No Record Found.', 'entrada' ); ?></td>
								</tr>
						<?php } ?>
							</tbody>
							<tfoot>
								<tr>
									<th width="13%">#</th>
									<th width="25%"><?php _e( 'Title', 'entrada' ); ?> </th>
									<th width="40%"><?php _e( 'Price Range', 'entrada' ); ?></th>
									<th width="22%"><?php _e( 'Action', 'entrada' ); ?></th>
								</tr>
							</tfoot>
						</table>
					</td>
				</tr>
			</table>
		</div>
		<?php
	}
}
	
/*  AddOns => Community Polls 
   ..................................... */
if ( ! function_exists( 'addons_community_polls' ) ) {
	function addons_community_polls() {
		global $wpdb;
		$page = isset($_REQUEST['page'])?$_REQUEST['page']:'';
		$mode = isset($_REQUEST['mode'])?$_REQUEST['mode']:'';
		$message = '';
		
		if( isset( $_POST['bannerbtn'] ) ) { 
			if( $mode=='edit' ){
				$wpdb->update($wpdb->prefix.'polls',array('poll_question'=>addslashes($_POST['poll_question']), 'poll_options'=>$_POST['poll_options']) , array('id'=>$_POST['bannerid']));
			}
			else{
				$wpdb->insert($wpdb->prefix.'polls', array('poll_question'=>addslashes($_POST['poll_question']), 'poll_options'=>$_POST['poll_options']) );
			}		
			$message = __( 'Record has been saved.', 'entrada' );
		}	
		if( $mode == 'delete' ) {
			$wpdb->query("delete from ".$wpdb->prefix."polls where id=$_REQUEST[pid]");
			$message = __( 'Record has been deleted.', 'entrada' );
		} ?>
		<div id="wrap">
			<div class="wrap">
				<h2> <img src="<?php echo get_template_directory_uri(); ?>/admin/img/addons.png"><?php _e( 'Community Polls', 'entrada' ); ?>
				<a href="<?php echo $_SERVER["PHP_SELF"]?>?page=community-polls&mode=add" class="button button-primary button-small" ><?php _e( 'Add New', 'entrada' ); ?></a> 
				</h2>
			</div>
		<?php if(!empty($message)) : ?>
			<div class="wrap"> <div id="message" class="updated" style="margin-left:0; padding:10px;"><?php echo $message; ?></div></div>
		<?php endif; ?>
			<table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
				<tr>
					<td width="40%" >
						<table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
							<form name="bannerfrm" action="" method="post" enctype="multipart/form-data">
						<?php 
							if( $mode == 'edit' ){
								$result_update = $wpdb->get_row("select * from ".$wpdb->prefix."polls where id=$_REQUEST[pid]");
							} ?>
							   <thead>
									<tr>
										<th> <strong>
										<?php
											if($mode=='edit') {
												echo __( 'Update', 'entrada' );
											}
											else { 
												echo __( 'Add', 'entrada' );
											}
											_e( 'Community Polls', 'entrada' ); ?></strong>
										</th>
									</tr>
								</thead>
								
								<tbody>
									<tr>
										<td>
											<label> <?php _e( 'Questions', 'entrada' ); ?> : </label>  <br /> <input type="text" name="poll_question" style="width:100%;"  id="poll_question" value="<?php if($mode=='edit') { echo stripslashes($result_update->poll_question); }?>"  />
											<input type="hidden" name="bannerid" value="<?php if($mode=='edit')echo $result_update->id;?>" />
											<p class="howto"> <?php _e( 'Please add questions here.', 'entrada' ); ?> </p>
										</td>
									</tr>
									<tr>
										<td>
											<label> <?php _e( 'Options', 'entrada' ); ?> : </label> <br />
											<textarea name="poll_options" id="poll_options"  style="width:100%; height:60px;" ><?php if($mode=='edit') { echo stripslashes($result_update->poll_options); }?></textarea>
											<p class="howto"> 
											<?php 
												$thisurl = 'https://developers.facebook.com/docs/apps/register';
												_e( 'Please add question\'s options here. Separate options with "%%". ( E. g. <code> the time of day%% the speaker%% your prejudices%% all of the above.</code>)', 'entrada' ); ?>
										</td>
									</tr>
									<tr>
										<td><input type="submit" class="button button-primary button-large" name="bannerbtn"  value="<?php esc_attr_e('Save', 'entrada'); ?>" style="cursor:pointer;" /></td>
									</tr>
								</tbody>
							   
							   <tfoot>
									<tr>
										<th>
										<?php 
											$thisurl = admin_url( 'widgets.php');
											echo sprintf( wp_kses( __( '<strong>Note</strong>: Please <a href="%s">click here</a> to activate poll in sidebar.', 'entrada' ), array(  'a' => array( 'href' => array() ) ) ), esc_url( $thisurl ) ); ?>
										</th>
									</tr>
								</tfoot>
							  
							</form>
						</table>
					</td>
					<td width="60%">
						<table width="100%" class="widefat fixed comments"  style="padding-bottom:20px;">
							<thead>
								<tr>
									<th width="5%">#</th>
									<th width="31%"><?php _e("Questions", "entrada"); ?> </th>
									<th width="20%"><?php _e("Options", "entrada"); ?></th>
									<th width="15%"><?php _e("Date", "entrada"); ?></th>
									<th width="12%"><?php _e("Active Poll", "entrada"); ?></th>
									<th width="15%"><?php _e("Actions", "entrada"); ?></th>
								</tr>
							</thead>
							<tbody>
						<?php
								$result = $wpdb->get_results("select * from ".$wpdb->prefix."polls WHERE 1= 1 order by id DESC ");
								$active_poll_id =  entrada_active_poll();
								if( $result ) {
									$count = 1;
									$class = '';
									foreach( $result as $entry ) {
										$total_vote = entrada_count_poll_option_result( $entry->id, '' );
										if($count%2 == 1){
											$class = 'class="alternate "';
										}
										else{
											$class = '';
										} ?>
						 
										<tr <?php echo $class; ?>>
											<td><?php echo $count; ?></td>
											<td><?php echo stripslashes($entry->poll_question); ?></td> 
											<td><?php 
												$poll_options = explode('%%', $entry->poll_options ); 
												$datapoints = array();
												$title = array();
												if(count($poll_options) > 0){
													$cnt = 0;
													echo '<ul class="poll_options">';
													foreach($poll_options as $opt){
														$cnt++;
														echo '<li>'.ucwords($opt).'</li>';
														/* Graph data start here */
															$option_vote = entrada_count_poll_option_result( $entry->id, $cnt );
															$vote_percentage = entrada__poll_option_vote_percentage($total_vote, $option_vote);
															if( empty( $vote_percentage ) ){
																$vote_percentage = 0;
															}
															$datapoints[] = array(
																				 "headline" 	=> $opt,
																				 "value" 		=> intval($vote_percentage),
																				 "length" 		=> 100,
																				 "description" 	=> $opt. ', Vote : '.$option_vote.', Percentage : '.intval($vote_percentage).'%'
																				);
														/* Graph data ends here */	
													}
													echo '</ul>';
												} ?>
												<script type="text/javascript">
													jQuery(document).ready(function() {
														object = <?php echo json_encode($datapoints); ?>;
														jQuery("#entrada-pie-chart-<?php echo $entry->id; ?>").skillset({
																		object:object,
																		duration:40
																	});
													});
												</script>
								
											</td>
											<td><?php echo date('Y-m-d', strtotime($entry->added_date) );  ?></td> 
											
											<td>
											<?php if(!empty($active_poll_id) && $active_poll_id == $entry->id){
													echo '<img title="Active Poll" src="'. get_template_directory_uri().'/admin/img/active.png">';
												} ?>
											</td>
											<td><a href="#TB_inline?width=340&height=450&inlineId=poll-result-<?php echo $entry->id; ?>" class="thickbox"><img src="<?php echo get_template_directory_uri(); ?>/admin/img/graph.png" title="View Result"> </a> &nbsp;<a href="<?php echo $_SERVER["PHP_SELF"]?>?page=<?php echo $page;?>&pid=<?php echo $entry->id;?>&mode=edit"><img src="<?php echo get_template_directory_uri(); ?>/admin/img/edit.png" title="Edit"></a> &nbsp;<a href="<?php echo $_SERVER["PHP_SELF"]?>?page=<?php echo $page;?>&pid=<?php echo $entry->id;?>&mode=delete" onclick="return confirm('Are you sure you want to delete?')"><img src="<?php echo get_template_directory_uri(); ?>/admin/img/delete.png" title="Delete"> </a></td>
										</tr> 
									<?php
										$count++;
									}
								}
								else { ?>
									<tr class="alternate ">
										<td colspan="6"><?php _e("No Record Found.", "entrada"); ?></td>
									</tr>
							<?php } ?>
							</tbody>
							<tfoot>
								<tr>
									<th width="5%">#</th>
									<th width="31%"><?php _e("Questions", "entrada"); ?> </th>
									<th width="20%"><?php _e("Options", "entrada"); ?></th>
									<th width="15%"><?php _e("Date", "entrada"); ?></th>
									<th width="12%"><?php _e("Active Poll", "entrada"); ?></th>
									<th width="15%"><?php _e("Actions", "entrada"); ?></th>
								</tr>
							</tfoot>
						</table>
					</td>
				</tr>
			</table>
		<?php
		if( $result ) {
			foreach( $result as $entry ) {
				$total_vote = entrada_count_poll_option_result( $entry->id, '' ); ?>
				<div id="poll-result-<?php echo $entry->id; ?>" style="display:none;">
					<p class="question_title">Q. <?php echo stripslashes($entry->poll_question); ?> </p>
					<div id="entrada-pie-chart-<?php echo $entry->id; ?>" class="column"> </div>
					<p class="question_title"> <strong><?php _e( 'Total Votes', 'entrada' ); ?> : <?php echo $total_vote; ?></strong></p>
				</div> 
		<?php
			}
		} ?>
		</div>
		<style>
			.poll_options{margin:0; padding:0;}
			.poll_options li{list-style: lower-alpha;}
			.question_title{ padding-bottom:20px;}
		</style>
	<?php
	}
}

if ( ! function_exists( 'get_entrada_option' ) ) {
	function get_entrada_option($entrada_key) {
		global $wpdb;
		$sql = "select entrada_value from ".$wpdb->prefix."entrada_options where entrada_key= '".$entrada_key."'";
		$result = $wpdb->get_row($sql);
		if(count($result) > 0){
			return $result->entrada_value;
		}
		else{
			return '';
		}
	}
}

if ( ! function_exists( 'update_entrada_option' ) ) {
	function update_entrada_option($entrada_key, $entrada_value) {
		global $wpdb;
		$sql = "select entrada_value from ".$wpdb->prefix."entrada_options where entrada_key= '".$entrada_key."'";
		$result = $wpdb->get_row($sql);
		if(count($result) > 0) {
			$wpdb->update(
				$wpdb->prefix.'entrada_options',
				array('entrada_value' => $entrada_value ),
				array( 'entrada_key' => $entrada_key )
			); 
		}
		else{
			$wpdb->insert(
				$wpdb->prefix.'entrada_options',
				array(
					'entrada_value' => $entrada_value,
					'entrada_key' => $entrada_key,
					'entrada_autoload' => 'yes' 
				  )
			);
		}		
	}
} ?>